### PR TITLE
Improved network interface filtering

### PR DESCRIPTION
**Pull request by graytonio**
I improved the filtering of the network interfaces to ignore things like virtual ethernet interfaces and interfaces created by docker.

### CODE REVIEW

**Comment by Mantrain** [comment]
This is just what is was looking for, thanks!

**Comment by Syntax3rror404** [comment]
@xezpeleta please merge that. This fixed the issue with kubernetes hosts network interfaces also. If I sync the inventory I get the wrong ip addresses.

**Comment by Syntax3rror404** [comment]
But we also need to filter flannel and calico (kubernetes) ips out

**Comment by Mantrain** [comment]
> But we also need to filter flannel and calico (kubernetes) ips out

Should be fairly easy to add this yourself, if you look at the changes @graytonio  did.
I just gave up on filtering stuff, and instead hardcoded the interface i want it to report from.

**Comment by graytonio** [comment]
I think a better solution looking back on this now is to have a configurable include/exclude filter for network interfaces instead of trying to apply a catch all solution.  I don't know if I'll have time to implement it but if I find some time in the coming days I'll make the changes to my fork.

**Comment by xezpeleta** [comment]
> I think a better solution looking back on this now is to have a configurable include/exclude filter for network interfaces instead of trying to apply a catch all solution.  I don't know if I'll have time to implement it but if I find some time in the coming days I'll make the changes to my fork.

I agree. If you implement it i'll merge the PR.

Thank you very much

**Comment by graytonio** [comment]
@xezpeleta Added the feature in. I have them as mutually exclusive fields and prioritizes include before exclude.  Also updated the config so by default it will include every interface. Did some basic testing with it locally but let me know if you find any issues with it.

**Comment by xezpeleta** [comment]
@graytonio merged! Good job 👏

Thank you!!!

**Pull request merged**
